apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/do/deploy.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
  - cluster_issuer.yaml
  - ingress.yaml

patches:
  - path: ingress_nginx_svc.yaml
